credits/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_task.urls')),
]

test_task/urls.py
# Django:
from django.urls import path

# Localfolder:
from . import views

app_name = "test_task"

urlpatterns = [
    path("", views.contracts_list, name="contracts-list"),
    path("<int:pk>/", views.contract_detail, name="contract-detail"),
]

test_task/models.py
from django.db import models


# Create your models here.

class Manufacturer(models.Model):
    create_manufacturer_date = models.DateTimeField(auto_now_add=True)
    manufacturer_name = models.CharField(max_length=100)

    def __str__(self):
        return self.manufacturer_name


class Contract(models.Model):
    create_contract_date = models.DateTimeField(auto_now_add=True)
    description_contract = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.description_contract


class CreditApplication(models.Model):
    create_credit_date = models.DateTimeField(auto_now_add=True)
    description_application = models.CharField(max_length=300, null=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, related_name='contract_applications')

    def __str__(self):
        return self.description_application


class Product(models.Model):
    create_product_date = models.DateTimeField(auto_now_add=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=True, blank=True)
    product_name = models.CharField(max_length=100)
    credit_application = models.ForeignKey(CreditApplication, on_delete=models.CASCADE, null=True,
                                           blank=True)

    def __str__(self):
        return self.product_name

test_task/views.py
from django.shortcuts import render

# Create your views here.
from test_task.models import CreditApplication


def contracts_list(request):
    contracts = CreditApplication.objects.all()
    context = {"contracts": contracts}
    return render(request, "test_task/contracts_list.html", context)


def contract_detail(request, pk):
    contract = CreditApplication.objects.filter(contract__pk=pk).values_list("product__manufacturer__id",
                                                                             flat=True).distinct()
    context = {"contract": contract}
    # import pdb;
    # pdb.set_trace()
    return render(request, "test_task/contract_detail.html", context)

templates/test_task/application_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>{{ application }}</p>
</body>
</html>

templates/test_task/applications_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Производители</title>
</head>
<body>
<table border="1">
    <tr>
        <th>Дата:</th>
        <th>Товары:</th>
        <th>Контракт:</th>
    </tr>
    {% for application in applications_list %}
    <tr>
        <td>{{ application.create_credit_date }}</td>
        <td>{{ application.products }}</td>
        <td>{{ application.contract }}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

templates/test_task/contract_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% for manufacturer in contract %}
    <p>{{ manufacturer }}</p>
{% endfor %}
</body>
</html>

templates/test_task/contracts_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Производители</title>
</head>
<body>
<table border="1">
    <tr>
        <th>Дата:</th>
        <th>Контракт:</th>
    </tr>
    {% for contract in contracts %}
        <tr>
            <td>{{ contract.create_credit_date }}</td>
            <td><a class="btn btn-info"
                   href="{% url 'test_task:contract-detail' pk=contract.id %}">{{ contract.contract.id }}</a></td>
        </tr>
    {% endfor %}

</table>
</body>
</html>